import React, { useState, useRef, useEffect } from 'react';
import { Send, ShieldAlert } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// Interfaces
interface Message {
  role: 'user' | 'model';
  parts: { text: string }[];
}

interface DocumentInfo {
  id: string;
  originalName: string;
  uploadedAt: string;
  source?: 'upload' | 'local';
}

export default function App() {
  return (
    <div className="flex h-screen bg-neutral-50 text-neutral-900 font-sans">
      <div className="flex flex-col w-full h-full">
        <header className="bg-white border-b border-neutral-200 px-4 py-3 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2">
            <ShieldAlert className="w-6 h-6 text-emerald-600" />
            <h1 className="font-semibold text-lg tracking-tight">EcoCheck FAQ</h1>
          </div>
        </header>

        <main className="flex-1 overflow-hidden relative">
          <ChatView />
        </main>
      </div>
    </div>
  );
}

// === CHAT COMPONENT ===

function renderInlineBold(text: string) {
  const segments = text.split(/(\*\*[^*]+\*\*)/g);
  return segments.map((segment, index) => {
    if (segment.startsWith('**') && segment.endsWith('**')) {
      return <strong key={index}>{segment.slice(2, -2)}</strong>;
    }
    return <React.Fragment key={index}>{segment}</React.Fragment>;
  });
}

function renderBasicMarkdown(text: string) {
  const lines = text.split('\n');
  return lines.map((line, index) => {
    const bulletMatch = line.match(/^\s*\*\s+(.*)$/);
    if (bulletMatch) {
      return (
        <div key={index} className="pl-1">
          • {renderInlineBold(bulletMatch[1])}
        </div>
      );
    }

    return <div key={index}>{renderInlineBold(line)}</div>;
  });
}

function ChatView() {
  const [messages, setMessages] = useState<Message[]>([
    { role: 'model', parts: [{ text: '您好！歡迎使用生態檢核智能諮詢系統。請輸入您關於生態檢核的任何問題，系統將依據專業規範與專案文件為您提供精準、可靠的解答。' }] }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userMsg: Message = { role: 'user', parts: [{ text: input.trim() }] };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setIsLoading(true);

    // Filter out initial greeting if it doesn't match API expected format or just pass everything.
    // Actually, backend needs specific format: [ {role: "user" | "model", parts: [{text: "..."}]} ]
    // The initial greeting is technically generated by us, but it's safe to include.
    
    try {
      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: [...messages, userMsg] })
      });
      
      const data = await res.json();
      
      if (res.ok) {
        setMessages(prev => [...prev, { role: 'model', parts: [{ text: data.response }] }]);
      } else {
        setMessages(prev => [...prev, { role: 'model', parts: [{ text: `系統錯誤: ${data.error}` }] }]);
      }
    } catch (err) {
      setMessages(prev => [...prev, { role: 'model', parts: [{ text: '連接伺服器失敗，請稍後再試。' }] }]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full max-w-3xl mx-auto w-full">
      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 md:space-y-6">
        <AnimatePresence initial={false}>
          {messages.map((m, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className={cn(
                "flex w-full",
                m.role === 'user' ? "justify-end" : "justify-start"
              )}
            >
              <div 
                className={cn(
                  "px-4 py-3 rounded-2xl max-w-[85%] sm:max-w-[75%] shadow-sm",
                  m.role === 'user' 
                    ? "bg-emerald-600 text-white rounded-tr-none" 
                    : "bg-white border border-neutral-200 text-neutral-800 rounded-tl-none whitespace-pre-wrap"
                )}
              >
                {m.role === 'model' ? renderBasicMarkdown(m.parts[0].text) : m.parts[0].text}
              </div>
            </motion.div>
          ))}
        </AnimatePresence>

        {isLoading && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex justify-start">
            <div className="px-4 py-3 rounded-2xl bg-white border border-neutral-200 text-neutral-500 rounded-tl-none shadow-sm flex items-center gap-2">
              <span className="w-2 h-2 bg-neutral-300 rounded-full animate-bounce"></span>
              <span className="w-2 h-2 bg-neutral-300 rounded-full animate-bounce [animation-delay:0.2s]"></span>
              <span className="w-2 h-2 bg-neutral-300 rounded-full animate-bounce [animation-delay:0.4s]"></span>
            </div>
          </motion.div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="p-4 bg-neutral-50 border-t border-neutral-200 shrink-0">
        <form 
          onSubmit={handleSubmit}
          className="relative flex items-center shadow-sm bg-white border border-neutral-300 rounded-xl overflow-hidden focus-within:ring-2 focus-within:ring-emerald-500 focus-within:border-emerald-500 transition-all"
        >
          <input
            type="text"
            value={input}
            onChange={e => setInput(e.target.value)}
            disabled={isLoading}
            placeholder="請輸入關於生態檢核的問題..."
            className="flex-1 w-full border-0 py-3 md:py-4 pl-4 pr-12 text-sm sm:text-base outline-none bg-transparent disabled:opacity-50"
          />
          <button
            type="submit"
            disabled={!input.trim() || isLoading}
            className="absolute right-2 p-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 disabled:opacity-50 disabled:hover:bg-emerald-600 transition-colors"
          >
            <Send className="w-4 h-4" />
          </button>
        </form>
        <p className="text-center text-xs text-neutral-400 mt-2">AI 智能回覆內容僅供參考，實際規範與執行細節請依正式核定文件與專案合約為準。</p>
      </div>
    </div>
  );
}

